services:
  code-server:
    build: .
    container_name: code-server
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: Europe/Paris
      PASSWORD: ${CODE_SERVER_PASSWORD}
      DEFAULT_WORKSPACE: /projects
    volumes:
      - code_config:/config
      - code_projects:/projects
    restart: unless-stopped

volumes:
  code_config:
  code_projects:
